# Generated by Django 5.0.7 on 2025-09-09 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vottingapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('position', models.CharField(choices=[('president', 'President'), ('vice-president', 'Vice President'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('public-relations', 'Public Relations Officer')], max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('slogan', models.CharField(max_length=255)),
                ('manifesto', models.TextField()),
                ('profile_photo', models.ImageField(upload_to='candidate_photos/')),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'position')},
            },
        ),
    ]
