# Generated by Django 5.0.7 on 2025-09-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vottingapp', '0003_election_candidate_votes_customuser_has_voted_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
