# Generated by Django 5.0.7 on 2025-09-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vottingapp', '0004_remove_candidate_is_approved_candidate_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField(default=2022)),
                ('end_year', models.IntegerField(default=2025)),
                ('election_title', models.CharField(default='SOMASE Executive Election', max_length=255)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('additional_emails', models.TextField(blank=True, help_text='Additional eligible emails (one per line)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Election Settings',
            },
        ),
    ]
