# Generated by Django 5.0.7 on 2025-09-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vottingapp', '0005_electionsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('voter', 'Voter'), ('moderator', 'Moderator'), ('president', 'President')], default='voter', max_length=10),
        ),
    ]
