# Generated by Django 5.0.7 on 2025-09-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vottingapp', '0006_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('voter', 'Voter'), ('moderator', 'Moderator'), ('president', 'President'), ('vice_president', 'Vice President')], default='voter', max_length=30),
        ),
    ]
