# Generated by Django 5.0.7 on 2025-09-14 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vottingapp', '0007_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('candidate_approval', 'Candidate Approval'), ('candidate_rejection', 'Candidate Rejection'), ('election_start', 'Election Started'), ('election_end', 'Election Ended'), ('moderator_added', 'Moderator Added'), ('moderator_removed', 'Moderator Removed'), ('vice_president_set', 'Vice President Set'), ('presidency_transferred', 'Presidency Transferred'), ('settings_updated', 'Settings Updated')], max_length=50)),
                ('details', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('viewed_by', models.ManyToManyField(blank=True, related_name='viewed_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
