# Generated by Django 5.0.7 on 2025-09-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vottingapp', '0009_userauditlogdeletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionsettings',
            name='duration',
            field=models.PositiveIntegerField(default=60, help_text='Election duration in minutes'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='position',
            field=models.CharField(choices=[('president', 'President'), ('vice-president', 'Vice President'), ('general-secretary', 'General Secretary'), ('organising-secretary', 'Organising Secretary'), ('publicity-secretary', 'Publicity Secretary'), ('treasurer', 'Treasurer'), ('entertainment-director', 'Entertainment Director'), ('sports-director', 'Sports Director'), ('society-member', 'Society Member')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vote',
            name='position',
            field=models.CharField(choices=[('president', 'President'), ('vice-president', 'Vice President'), ('general-secretary', 'General Secretary'), ('organising-secretary', 'Organising Secretary'), ('publicity-secretary', 'Publicity Secretary'), ('treasurer', 'Treasurer'), ('entertainment-director', 'Entertainment Director'), ('sports-director', 'Sports Director'), ('society-member', 'Society Member')], max_length=50),
        ),
    ]
