# Generated by Django 5.0.7 on 2025-09-21 10:25

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vottingapp', '0011_customuser_email_verification_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='end_emails_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='election',
            name='start_emails_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='profile_photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='candidate_photo'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_photo'),
        ),
    ]
