# Generated by Django 5.0.7 on 2025-09-21 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vottingapp', '0012_election_end_emails_sent_election_start_emails_sent_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='vottingapp_user',
        ),
    ]
