# Generated by Django 5.0.7 on 2025-09-21 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vottingapp', '0013_alter_customuser_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='auth_user',
        ),
    ]
